### ISSUE TITLE
URL to point to the icons website

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#13]
What is the URL for the webpage that contains the icons to be used in e.g. the RowButtonGrid or icons to download docs?
To select a different icon is just to provide the name of the new icon or we also need to include e.g. a folder name?

**Comment by rubystream** [comment]
The icons used are from the https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=brands,solid&m=free collection.

For example the https://fontawesome.com/v5.15/icons/download?style=solid is referenced in `main/content/resources.md` as `icon: fas download`. The similar approach needs to be taken

**Comment by jpradocueva** [comment]
The URL has been added to the guidelines, https://openmobilealliance.github.io/githubpages-doc-guidelines/#description
