### ISSUE TITLE
Unable to run some modules in a new page

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#14]
@rubystream I have created a new branch https://github.com/OpenMobileAlliance/oma_github_pages/tree/test where I am analysing some of the modules.

In this branch, I have also created a new menu and page called "Test".
In the test.md page I have added some modules but the following modules don't run in this new page:

- [x] RowMultiColumns
- [ ] RowNewsList
- [ ] RowNewsCards
- [ ] RowButtonGrid
- [ ] RowEvents
Am I doing something wrong or these modules are not possible to run of a new page?

**Comment by rubystream** [comment]
There was some missing rendering of RowMultiColumns module. That is fixed not in test branch. Please try it out.
