### ISSUE TITLE
RowImage modules are not able to render icons

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#15]
It seems that the modules for Images, RowImageText, RowImage, is not able to render the icons from https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=brands,solid&m=free

Is this an intended limitation?

```md
  -
    name: RowImageText
    cols: 3
    image: fas arrow-alt-circle-down #/images/working_together_1.jpg
    status: #second-wide (extend the width of the image), "second" provides a background color to the text or empty
    text: | 
      ##### **Device Management & Service Enablement Working Group**
```

**Comment by rubystream** [comment]
The RowImageText currently do not support icons. 
Do you thing that it should ? If so I can add this support.

**Comment by jpradocueva** [comment]
We will see if there is a demand from the members or the public about it. I will close the PR.
