### ISSUE TITLE
RowNewsCards is not working in the test branch

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#16]
The module `RowNewsCards` is not working in the [`index.md`](https://raw.githubusercontent.com/OpenMobileAlliance/oma_github_pages/test/content/index.md) in the text branch.

> Note this `test` branch is not intended to be merged into `main`

```md
  -
    name: RowNewsCards
    news: 
```

**Comment by rubystream** [comment]
Provide #18 that should address this issue.
