### ISSUE TITLE
RowNewsCards don't render icons

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#17]
Same problem as Issue #15 
In the `test` branch, I have added an example to the **News** where the icons from the [fontawesome.org](https://fontawesome.com/v5.15/icons?d=gallery&p=2) don't render inside of NewsCards

See, https://raw.githubusercontent.com/OpenMobileAlliance/oma_github_pages/main/content/news/2021-03-02-uCIFI.md in the `test` branch.

```md
---
layout: news
image: /fas cog #/images/news/ucifi.png
title: uCIFI Alliance Contributes 29 Objects to OMA
description: description or insert a reference
subtitle: uCIFI Alliance collaborates with OMA LwM2M
url: 
by: OMA SpecWorks
date: 2021-Mar-02
homepage: 3
tags:
    - collaboration
---
```

**Comment by rubystream** [comment]
RowNewsCards currently do not support icons only images.

Do you thing we should create the support for icons as well?

**Comment by jpradocueva** [comment]
We will see if there is a demand from the members or the public about it. I will close the PR.
