### ISSUE TITLE
Problem open links to direct webpages

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#23]
A direct click on this link https://lwm2m.openmobilealliance.org/resources/ will show "404 Page not found"

**Comment by rubystream** [comment]
Is this still an issue?

**Comment by jpradocueva** [comment]
The problem was resolved by commit https://github.com/OpenMobileAlliance/oma_github_pages/commit/099abdc47ff9fe734f77f403d4ec7d0fe0b23292
