### ISSUE TITLE
Replace Resources Image with a new image

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#24]
Change the image in the resources page
https://lwm2m.openmobilealliance.org/resources/

**Comment by jpradocueva** [comment]
See PR #31 

New image
![image](https://user-images.githubusercontent.com/3258579/160202459-2afd4542-d08d-4b95-991e-291355b2543e.png)

**Comment by jpradocueva** [comment]
this didn't work,

.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}

**Comment by rubystream** [comment]
Image properly centered in commit https://github.com/OpenMobileAlliance/oma_github_pages/commit/d68a1b6ff3fb6390160ac7da2c7667e8ee5ad22a 

Changed from `RowTextImage` to `RowImage` module and apply needed CSS style to center the image.
