### ISSUE TITLE
Expose font-family in _custom.scss file

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#26]
In order to use be able to select a different types of fonts, we should add a new property `font-family` to the  `_custom.scss` file.

**Comment by jpradocueva** [comment]
These properties are already available in the file `_custom.scss`.

The `test` branch has updated the property `body` on the file `_custom.scss',  with the following information:

`font-size: larger`
`font-family: 'Roboto', 'Nunito Sans', 'Arial', 'Open Sans Light', 'Merriweather Sans', sans-serif;`

The types of 'font-family' (Roboto, Nunito Sans and Open Sans Light) don't seem to be working.

**Comment by jpradocueva** [comment]
Latest update on the `_custom.scss` file.

Line       | Property          | Prior Value           | New Value            | Comment
-------|--------------|-----------------|-----------------|---------------
1           |$primary          | #0c90e9               | #180A0A             |  Dark black color
13         | font-family     |'Merriweather Sans', sans-serif;  |  'Roboto', 'Nunito Sans', 'Arial', 'Open Sans Light', 'Merriweather Sans', sans-serif; | Roboto, Nunito Sans and Open Sans Light don't work
16        | font-size        | none                        | larger                    | increase font-size on the `body` element
253    | font-size         | 0.8rem                  | 1rem                       |  the class is `.row-button-grid .button-title`
259    | font-size       | 0.6rem                   | 0.9rem                   | the class is `.row-button-grid .button-subtitle`
264 | background-color | #cee5d0.       | #EFEFEF.              | the clas is  `.row-button-grid .active`
265 | color                     | #ff7878            | #180A0A             | the clas is  `.row-button-grid .active`
275 | background-color  | #e0c097  | #D1D1D1                | the class is `.row-button-grid .pending `
276 | color                   | #f06449  |   #180A0A                   | the class is `.row-button-grid .pending `

**Comment by jpradocueva** [comment]
This is how the above settings look like:

## Suggested Changes on Home Page
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/3258579/158180840-f546206c-06e7-4158-9bd3-1e9725c9d675.png">


## Current  Home Page
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/3258579/158180016-3c9d2229-ded6-4976-9f69-5b0d76275984.png">

## Difference 
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/3258579/158181223-ac935587-37bf-42ad-bfe9-f689b7088fcd.png">

**Comment by rubystream** [comment]
Added missing import statement for additional fonts.

**Comment by jpradocueva** [comment]
New `font-family: Nunito Sans`

## New Look & Feel
![image](https://user-images.githubusercontent.com/3258579/158483948-1d6f5c63-8ce8-435c-8c9b-4c083f7b5b8f.png)

**Comment by jpradocueva** [comment]
Waiting for members feedback.

**Comment by jpradocueva** [comment]
Approved by Jean Trakinat and merged.
