### ISSUE TITLE
Problem to access website links

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#28]
A click on the link https://lwm2m.openmobilealliance.org/blogs/2022-03-02-nuSIM_objects/ 

Provide this error message in Chrome

![image](https://user-images.githubusercontent.com/3258579/158654238-70aaff1b-7b1e-4a8e-8a85-7531e1531734.png)

and this error message in FireFox.
![image](https://user-images.githubusercontent.com/3258579/158655176-3819fa33-3501-44a9-b3fd-7ca40a9bbb79.png)

Do we need to have a certificate for this subdomain?

**Comment by rubystream** [comment]
I have find the missing required part for routing of static sites. It's a small config addition to generate these dynamic links.
The new version is merged to master, deployed and verified that is working as expected.

Please take a look as well.

**Comment by jpradocueva** [comment]
Commit https://github.com/OpenMobileAlliance/oma_github_pages/commit/099abdc47ff9fe734f77f403d4ec7d0fe0b23292 has resolved the problem.
