### ISSUE TITLE
Blog `filter-tags` has stopped working

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#30]
It appears that the filter of tags in the `blogs` pages is no longer working.

In the blogs page, https://lwm2m.openmobilealliance.org/blogs/ , click on the list of tags to filter the blogs. You will find that e.g. the nuSIM blog doesn't have any filter and it is listed despite selecting e.g. v1.2 tag.

**Comment by rubystream** [comment]
There was a missing processing when there was no Tags values defined. It's resolved and updated in the main branch.

**Comment by jpradocueva** [comment]
Problem resolved by https://github.com/OpenMobileAlliance/oma_github_pages/commit/7c6507402ca252e3cef60203ca330f5acd46122a
