### ISSUE TITLE
Inside of "News" file, homepage order is not working

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#35]
This PR https://github.com/OpenMobileAlliance/oma_github_pages/pull/34 combines "News" and "Blogs" under a single page.
The group decided to keep the layout "News". In the markdown files in `/content/news/` the property `homepage` with an integer should indicate in which order (top to bottom & left to right) the cards should be listed. 
It doesn't appear to work.

Branch to test this problem: https://github.com/OpenMobileAlliance/oma_github_pages/tree/information

**Comment by jpradocueva** [comment]
The PR was already merged, you can see the problem in the "main" branch.

**Comment by rubystream** [comment]
In the `news` page the order of news are related to the `date` parameter with the intention that latest news are presented at the beginning of that list.

The `homepage` parameter is introduced to enable selection and order of the news at the home page news widget.

If OMA would like to use different ordering of the news in the `news` page it can be easily introduced.

**Comment by gocadimic** [comment]
This repository is being archived, and this issue will not be addressed.
